Distributions: interactive HTML portion
naobservatory/scenario-simulator pull request #7
Opened 2024-10-25 02:35 UTC by jeffkaufman

This is the first step of updating the HTML to support allowing users to directly select the distributions we produce with P2RA.

It displays the intended interface and reacts appropriately when people click on things, but the simulation part is not coded yet and it doesn't work end to end.

You can play with this live at https://data.securebio.org/simulator/index-ww.html

The goal here is to review the interface we present to users before putting in the work to make it all functional.

@dp-rice for review I think it's fine to look only at the description of what is supposed to be happening and the user interface, and ignore the JS that makes it interactive.

2024-10-25 18:07 UTC, dp-rice requested changes
Some thoughts on the interface:
- It's not obvious that when you select a pathogen radio button that you're selecting the RA as opposed to just the genome length
- When you click on one of the swabs or custom it expands a relative abundance box. When you go from a wastewater sample to custom, this box is populated by a string that presumably is the key to get the P2RA distribution for that study/virus. It feels wrong to expose this to the user without explaining what it is (or how to customize it).

2024-10-25 19:16 UTC, jeffkaufman commented on html/index.html
> +          abundances we add lognormally distributed noise to the abundances
Reworded to multiply in f3c61b5.  The actual code is multiplying `empirical_value` by `lognormal(0, sigma)`.

2024-10-25 19:16 UTC, jeffkaufman commented on html/index.html
> +          with a geometric mean of zero and standard deviation of
Reworded in f3c61b5 to just say mu and sigma instead of trying to describe them in words.

2024-10-25 19:20 UTC, jeffkaufman commented on html/index.html
> +          when 1% of people became infected in the last week then 1e-7 of
I think this is not right either.  Reworded in 53ac1e2 to talk about the mean of the Poisson

2024-10-25 19:21 UTC, jeffkaufman commented on html/index.html
> +          &#963;<sub>g</sub>.  This noise shifts all provided values in the
Reworded in 5eba2ec

2024-10-25 19:26 UTC, jeffkaufman commented
> It's not obvious that when you select a pathogen radio button that you're selecting the RA as opposed to just the genome length

I think this is now fixed in 992abb4

2024-10-25 19:28 UTC, jeffkaufman commented
> When you click on one of the swabs or custom it expands a relative abundance box. When you go from a wastewater sample to custom, this box is populated by a string that presumably is the key to get the P2RA distribution for that study/virus. It feels wrong to expose this to the user without explaining what it is (or how to customize it).

Good point.  These aren't customizable, so made e20e97a to clear the box when selecting Custom.

2024-10-25 19:28 UTC, jeffkaufman commented
@dp-rice ready for re-review

2024-10-29 12:59 UTC, dp-rice approved these changes
Looks good!

2024-10-29 13:04 UTC, merged